name: sdk_xyo_flutter
description: XYO SDK for Flutter Projects
version: 0.1.0
homepage: https://github.com/XYOracleNetwork/sdk-xyo-flutter
author: Kevin Weiler <kevin.weiler@xyo.network>

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^1.0.0
  mutex: ^1.0.1
  retry: ^3.0.0+1
  fixnum: ^0.10.11

dev_dependencies:
  build_runner: ^1.0.0

  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: network.xyo.sdk_xyo_flutter
        pluginClass: SdkXyoFlutterPlugin
      ios:
        pluginClass: SdkXyoFlutterPlugin
