name: sdk_xyo_flutter
description: XYO SDK for Flutter Projects
version: 0.2.3
homepage: https://github.com/XYOracleNetwork/sdk-xyo-flutter

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^1.0.1
  mutex: ^1.1.0
  retry: ^3.0.0+1
  fixnum: ^0.10.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: network.xyo.sdk_xyo_flutter
        pluginClass: SdkXyoFlutterPlugin
      ios:
        pluginClass: SdkXyoFlutterPlugin

module:
  androidX: true
  androidPackage: network.xyo.sdk_xyo_flutter
  iosBundleIdentifier: network.xyo.sdkxyoflutter
