name: sdk_xyo_flutter
description: XYO SDK for Flutter Projects
version: 0.1.0
homepage: https://xyo.network

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^1.0.0
  mutex: ^1.0.1
  retry: ^3.0.0+1
  fixnum: ^0.10.11

dev_dependencies:
  build_runner: ^1.0.0

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: network.xyo.sdk_xyo_flutter
        pluginClass: SdkXyoFlutterPlugin
      pluginClass: SdkXyoFlutterPlugin
