name: build

on: 
  push:
    branches-ignore:
      - 'master'

jobs: 
  build: 
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,iOS=13.1,name=iPhone11']
    
    steps: 
      - uses: actions/checkout@v2
      - name: Pre-Build
        run: |
              gem install cocoapods-acknowledgements
              gem install cocoapods
              pod repo update
              pip install six
              git clone https://github.com/flutter/flutter.git --depth 1 -b beta
              $GITHUB_WORKSPACE/flutter/bin/flutter doctor
              
      - name: Build
        run: |
              $GITHUB_WORKSPACE/flutter/bin/flutter emulators --launch apple_ios_simulator
              cd $GITHUB_WORKSPACE/example
              $GITHUB_WORKSPACE/flutter/bin/flutter build ios -allowProvisioningUpdates
