name: Publish Release

on: 
  push:
    branches:
      - 'master'

jobs: 
  build: 
    runs-on: macOS-latest
    
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Pre Build
        uses: steebchen/flutter@v1.0.0
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b beta
          $GITHUB_WORKSPACE/flutter/bin/flutter doctor
      - name: Build
        uses: steebchen/flutter@v1.0.0
        run: |
          cd $GITHUB_WORKSPACE && bash $GITHUB_WORKSPACE/scripts/build.sh
      - name: Publish Package
        uses: steebchen/flutter@v1.0.0
        run: cd $GITHUB_WORKSPACE && bash $GITHUB_WORKSPACE/scripts/deploy.sh