name: Publish Release

on: 
  push:
    branches:
      - 'master'

jobs: 
  build: 
    runs-on: macOS-latest
    
    steps: 
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'  
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE && bash $GITHUB_WORKSPACE/scripts/build.sh
      - name: publish
        run: |
          cd $GITHUB_WORKSPACE && bash $GITHUB_WORKSPACE/scripts/deploy.sh